### ISSUE TITLE
Errors Warnings and Runtime Column Value only for last simulation

### ISSUE THREAD

**Issue by JasonGlazer** [NREL/EP-Launch#35]
The columns showing the errors, warnings and runtime only show up for the last simulation run in a directory.  The .eplaunch3 cache file also shows that only the last file has these values.

**Comment by Myoldmopar** [comment]
I think I reproduced this locally.  I have a folder with 3 idfs in it.  I can run each file separately and the cache file seems to have all the data compiled up.  But then if I run two of them at once, the results come back for those, but now the results from the first one disappear.  I'll investigate.

**Comment by Myoldmopar** [comment]
Can you take a look at the new master branch -- sorry I should be doing these on a separate branch but I keep thinking I'm just one commit away -- and see if you see it behaving any better?  I am now seeing perfect behavior on that issue I was able to reproduce.  There was a problem where the interface would try to keep a second copy of the cache file and it would be too late to get the next set of results.  Now the read/write is all mutex-ed away within a single call to the write functions, so there should be no chance of weird mismatched responses.

Aaannnnd I just saw Travis failed my push to master...awesome.  I'll get it fixed up.

**Comment by Myoldmopar** [comment]
OK, master is all fixed up.  I also got the docs building on ReadTheDocs again.  Once I added in automodule to parse and document our classes, RTD failed because our code requires Python 3.5+.  I switched the interpreter over in RTD and all is well.  It looks pretty [sweet](https://ep-launch.readthedocs.io/en/latest/cache.html#cache-module-auto-documentation).  Please take a look and close this issue if it looks like it's good to go again for you.

**Comment by JasonGlazer** [comment]
I think you resolved this issue. I'm going to have to remember this fixing issues on the master branch thing :-)

RTD looks nice, we should probably add a link to the readme.md
